// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisableTunnel():Promise<main.WebhookResponse>;

export function EnableTunnel():Promise<main.WebhookResponse>;

export function GetStatus():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function StartWebhook(arg1:number,arg2:boolean):Promise<main.WebhookResponse>;

export function StopWebhook():Promise<void>;
