// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableTunnel() {
  return window['go']['main']['App']['DisableTunnel']();
}

export function EnableTunnel() {
  return window['go']['main']['App']['EnableTunnel']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartWebhook(arg1, arg2) {
  return window['go']['main']['App']['StartWebhook'](arg1, arg2);
}

export function StopWebhook() {
  return window['go']['main']['App']['StopWebhook']();
}
